#! /bin/sh
# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███?
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-1 --same-as eDP-1

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Zathura state=tiled

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
nitrogen --restore &
polybar mybar &
