[colors]

[colors.bright]
black = "#5c5855"
blue = "#01a0e4"
cyan = "#b5e4f4"
green = "#01a252"
magenta = "#a16a94"
red = "#db2d20"
white = "#f7f7f7"
yellow = "#fded02"

[colors.cursor]
cursor = "#a5a2a2"
text = "#090300"

[colors.normal]
black = "#090300"
blue = "#01a0e4"
cyan = "#b5e4f4"
green = "#01a252"
magenta = "#a16a94"
red = "#db2d20"
white = "#a5a2a2"
yellow = "#fded02"

[colors.primary]
background = "#0d0d0d"
foreground = "#a5a2a2"

[font]
size = 6.0

[font.normal]
family = "monospace"
style = "Regular"

[shell]
program = "/bin/zsh"
